name: Hue action

on:
  push:
    branches: [master]

jobs:
  hue-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: manekinekko/hue-action@v1.0
        with:
          hueWebhook: ${{ secrets.HUEACTION_WEBHOOK }}
          hueLightId: "13"
          hueStatus: "#ffd53d"

      - uses: manekinekko/hue-action@v1.0
        if: success()
        with:
          hueWebhook: ${{ secrets.HUEACTION_WEBHOOK }}
          hueLightId: "13"
          hueStatus: "success"

      - uses: manekinekko/hue-action@v1.0
        if: failure()
        with:
          hueWebhook: ${{ secrets.HUEACTION_WEBHOOK }}
          hueLightId: "13"
          hueStatus: "failure"
