name: Hue action

on:
  push:
    branches: [master]

jobs:
  build:
	  steps:
      - name: Run Hue Action
      - uses: manekinekko/hue-action@v1.0
        if: success()
        with:
        hueWebhook: ${{ secrets.HUEACTION_WEBHOOK }}
        hueLightId: "13"
        hueStatus: "success"
